<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="QSINBNB342" failures="1" tests="1" name="Test(failed)" time="18.265" errors="0" timestamp="2023-08-09T14:00:00 IST">
  <testcase classname="Code.TC1_Login" name="LoginWithOutCredential" time="6.372">
    <failure type="java.lang.AssertionError" message="expected [Please fill this fieldd.] but found [Please fill this field.]">
      <![CDATA[java.lang.AssertionError: expected [Please fill this fieldd.] but found [Please fill this field.]
at Code.TC1_Login.LoginWithOutCredential(TC1_Login.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginWithOutCredential -->
  <testcase classname="Code.TC1_Login" name="LoginWithInvalidUser" time="0.0">
    <ignored/>
  </testcase> <!-- LoginWithInvalidUser -->
  <testcase classname="Code.TC1_Login" name="LoginWithInvalidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- LoginWithInvalidPassword -->
  <testcase classname="Code.TC1_Login" name="loginWithValidCredential" time="0.0">
    <ignored/>
  </testcase> <!-- loginWithValidCredential -->
</testsuite> <!-- Test(failed) -->
